=== Diferti/sql-on-fhir-v2/tests/tests.schema.json
{
  "$id" : "https://sof.fhir.org/tests",
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "title" : "SQL on FHIR Tests Schema",
  "description" : "Schema for tests",
  "type" : "object",
  "required" : [ "title" ],
  "properties" : {
    "title" : {
      "type" : "string"
    },
    "description" : {
      "type" : "string"
    },
    "authors" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "generated" : {
      "type" : "boolean"
    },
    "resources" : {
      "type" : "array",
      "items" : {
        "type" : "object"
      }
    },
    "tests" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "required" : [ "title", "view", "expected" ],
        "properties" : {
          "title" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "view" : {
            "$ref" : "#/$defs/view"
          },
          "expected" : {
            "type" : "array",
            "items" : {
              "type" : "object"
            }
          }
        }
      }
    }
  },
  "$defs" : {
    "view" : {
      "type" : "object",
      "resource" : {
        "type" : "string"
      },
      "select" : {
        "type" : "array",
        "items" : {
          "type" : "object",
          "properties" : {
            "path" : {
              "type" : "string"
            },
            "name" : {
              "type" : "string"
            },
            "forEach" : {
              "type" : "object"
            },
            "forOrNul" : {
              "type" : "object"
            },
            "union" : {
              "type" : "object"
            },
            "tags" : {
              "type" : "array",
              "items" : {
                "type" : "object",
                "required" : [ "name", "value" ],
                "property" : {
                  "name" : {
                    "type" : "string"
                  },
                  "value" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      },
      "where" : {
        "type" : "array",
        "items" : {
          "type" : "object",
          "required" : [ "path" ],
          "properties" : {
            "path" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}

=== Diferti/sql-on-fhir-v2/tests/fn_boundary.json
{
 "title": "fn_boundary",
 "description": "TBD",
 "resources": [
  {
   "resourceType": "Observation",
   "id": "o1",
   "code": {
    "text": "code"
   },
   "status": "final",
   "valueQuantity": {
    "value": 1
   }
  },
  {
   "resourceType": "Observation",
   "id": "o2",
   "code": {
    "text": "code"
   },
   "status": "final",
   "valueDateTime": "2010-10-10"
  },
  {
   "resourceType": "Observation",
   "id": "o3",
   "code": {
    "text": "code"
   },
   "status": "final"
  }
 ],
 "tests": []
}

=== Diferti/sql-on-fhir-v2/sof-tests/foreach.json
{
 "title": "foreach",
 "description": "TBD",
 "resources": [
  {
   "id": "pt1",
   "name": [
    {
     "family": "F1.1"
    },
    {
     "family": "F1.2"
    }
   ],
   "contact": [
    {
     "type": "T1",
     "person": [
      {
       "name": "N1"
      },
      {
       "name": "N1`"
      }
     ]
    },
    {
     "type": "T2",
     "person": [
      {
       "name": "N2"
      }
     ]
    }
   ]
  },
  {
   "id": "pt2",
   "name": [
    {
     "family": "F2.1"
    },
    {
     "family": "F2.2"
    }
   ]
  },
  {
   "id": "pt3"
  }
 ],
 "tests": [
  {
   "title": "forEach: normal",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     },
     {
      "forEach": "name",
      "select": [
       {
        "column": [
         {
          "name": "family",
          "path": "family"
         }
        ],
        "type": "column"
       }
      ],
      "type": "forEach"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "family": "F1.1"
    },
    {
     "id": "pt1",
     "family": "F1.2"
    },
    {
     "id": "pt2",
     "family": "F2.1"
    },
    {
     "id": "pt2",
     "family": "F2.2"
    }
   ]
  },
  {
   "title": "forEachOrNull: normal",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     },
     {
      "forEachOrNull": "name",
      "select": [
       {
        "column": [
         {
          "name": "family",
          "path": "family"
         }
        ],
        "type": "column"
       }
      ],
      "type": "forEachOrNull"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "family": "F1.1"
    },
    {
     "id": "pt1",
     "family": "F1.2"
    },
    {
     "id": "pt2",
     "family": "F2.1"
    },
    {
     "id": "pt2",
     "family": "F2.2"
    },
    {
     "id": "pt3",
     "family": null
    }
   ]
  },
  {
   "title": "forEach: empty",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     },
     {
      "forEach": "identifier",
      "select": [
       {
        "column": [
         {
          "name": "value",
          "path": "value"
         }
        ],
        "type": "column"
       }
      ],
      "type": "forEach"
     }
    ],
    "type": "select"
   },
   "expected": []
  },
  {
   "title": "forEachOrNull: null case",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     },
     {
      "forEachOrNull": "identifier",
      "select": [
       {
        "column": [
         {
          "name": "value",
          "path": "value"
         }
        ],
        "type": "column"
       }
      ],
      "type": "forEachOrNull"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "value": null
    },
    {
     "id": "pt2",
     "value": null
    },
    {
     "id": "pt3",
     "value": null
    }
   ]
  },
  {
   "title": "nested forEach",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     },
     {
      "forEach": "contact",
      "select": [
       {
        "column": [
         {
          "name": "contact_type",
          "path": "type"
         }
        ],
        "type": "column"
       },
       {
        "forEach": "person",
        "select": [
         {
          "column": [
           {
            "name": "name",
            "path": "name"
           }
          ],
          "type": "column"
         }
        ],
        "type": "forEach"
       }
      ],
      "type": "forEach"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "contact_type": "T1",
     "name": "N1",
     "id": "pt1"
    },
    {
     "contact_type": "T1",
     "name": "N1`",
     "id": "pt1"
    },
    {
     "contact_type": "T2",
     "name": "N2",
     "id": "pt1"
    }
   ]
  },
  {
   "title": "nested forEach: select & column",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     },
     {
      "forEach": "contact",
      "select": [
       {
        "column": [
         {
          "name": "contact_type",
          "path": "type"
         }
        ],
        "type": "column"
       },
       {
        "forEach": "person",
        "select": [
         {
          "column": [
           {
            "name": "name",
            "path": "name"
           }
          ],
          "type": "column"
         }
        ],
        "type": "forEach"
       }
      ],
      "type": "forEach"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "contact_type": "T1",
     "name": "N1",
     "id": "pt1"
    },
    {
     "contact_type": "T1",
     "name": "N1`",
     "id": "pt1"
    },
    {
     "contact_type": "T2",
     "name": "N2",
     "id": "pt1"
    }
   ]
  }
 ]
}

=== Diferti/sql-on-fhir-v2/sof-tests/fhirpath.json
{
 "title": "fhirpath",
 "description": "fhirpath features",
 "resources": [
  {
   "resourceType": "Patient",
   "id": "pt1",
   "managingOrganization": {
    "reference": "Organization/o1"
   },
   "name": [
    {
     "family": "f1.1",
     "use": "official",
     "given": [
      "g1.1.1",
      "g1.1.2"
     ]
    },
    {
     "family": "f1.2",
     "given": [
      "g1.2.1"
     ]
    }
   ],
   "active": true
  },
  {
   "resourceType": "Patient",
   "id": "pt2",
   "managingOrganization": {
    "reference": "http://myapp.com/prefix/Organization/o2"
   },
   "name": [
    {
     "family": "f2.1"
    },
    {
     "family": "f2.2",
     "use": "official"
    }
   ],
   "active": false
  },
  {
   "resourceType": "Patient",
   "id": "pt3"
  }
 ],
 "tests": [
  {
   "title": "one element",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1"
    },
    {
     "id": "pt2"
    },
    {
     "id": "pt3"
    }
   ]
  },
  {
   "title": "two elements + first",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "v",
        "path": "name.family.first()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "v": "f1.1"
    },
    {
     "v": "f2.1"
    },
    {
     "v": null
    }
   ]
  },
  {
   "title": "collection",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "v",
        "path": "name.family",
        "collection": true
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "v": [
      "f1.1",
      "f1.2"
     ]
    },
    {
     "v": [
      "f2.1",
      "f2.2"
     ]
    },
    {
     "v": []
    }
   ]
  },
  {
   "title": "index[0]",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "v",
        "path": "name[0].family"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "v": "f1.1"
    },
    {
     "v": "f2.1"
    },
    {
     "v": null
    }
   ]
  },
  {
   "title": "index[1]",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "v",
        "path": "name[1].family"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "v": "f1.2"
    },
    {
     "v": "f2.2"
    },
    {
     "v": null
    }
   ]
  },
  {
   "title": "out of index",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "v",
        "path": "name[2].family"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "v": null
    },
    {
     "v": null
    },
    {
     "v": null
    }
   ]
  },
  {
   "title": "where",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "v",
        "path": "name.where(use='official').family"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "v": "f1.1"
    },
    {
     "v": "f2.2"
    },
    {
     "v": null
    }
   ]
  },
  {
   "title": "exists",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "has_name",
        "path": "name.exists()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "has_name": true
    },
    {
     "id": "pt2",
     "has_name": true
    },
    {
     "id": "pt3",
     "has_name": false
    }
   ]
  },
  {
   "title": "nested exists",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "has_given",
        "path": "name.given.exists()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "has_given": true
    },
    {
     "id": "pt2",
     "has_given": false
    },
    {
     "id": "pt3",
     "has_given": false
    }
   ]
  },
  {
   "title": "exists",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "first_given",
        "path": "name.given.first()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "first_given": "g1.1.1"
    },
    {
     "id": "pt2",
     "first_given": null
    },
    {
     "id": "pt3",
     "first_given": null
    }
   ]
  },
  {
   "title": "exists",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "first_family",
        "path": "name.family.first()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "first_family": "f1.1"
    },
    {
     "id": "pt2",
     "first_family": "f2.1"
    },
    {
     "id": "pt3",
     "first_family": null
    }
   ]
  },
  {
   "title": "string join",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "given",
        "path": "name.given.join(', ' )"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "given": "g1.1.1, g1.1.2, g1.2.1"
    },
    {
     "id": "pt2",
     "given": ""
    },
    {
     "id": "pt3",
     "given": ""
    }
   ]
  },
  {
   "title": "string join: default separator",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "given",
        "path": "name.given.join()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "given": "g1.1.1g1.1.2g1.2.1"
    },
    {
     "id": "pt2",
     "given": ""
    },
    {
     "id": "pt3",
     "given": ""
    }
   ]
  },
  {
   "title": "getResourceKey()",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "getResourceKey()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "Patient/pt1"
    },
    {
     "id": "Patient/pt2"
    },
    {
     "id": "Patient/pt3"
    }
   ]
  },
  {
   "title": "getReferenceKey()",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "ref",
        "path": "managingOrganization.getReferenceKey()"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "ref": "Organization/o1"
    },
    {
     "id": "pt2",
     "ref": "Organization/o2"
    },
    {
     "id": "pt3",
     "ref": null
    }
   ]
  },
  {
   "title": "getReferenceKey(<type>)",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "ref",
        "path": "managingOrganization.getReferenceKey('Organization')"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "ref": "Organization/o1"
    },
    {
     "id": "pt2",
     "ref": "Organization/o2"
    },
    {
     "id": "pt3",
     "ref": null
    }
   ]
  },
  {
   "title": "getReferenceKey(<type>)",
   "view": {
    "select": [
     {
      "column": [
       {
        "name": "id",
        "path": "id"
       },
       {
        "name": "ref",
        "path": "managingOrganization.getReferenceKey('Encounter')"
       }
      ],
      "type": "column"
     }
    ],
    "type": "select"
   },
   "expected": [
    {
     "id": "pt1",
     "ref": null
    },
    {
     "id": "pt2",
     "ref": null
    },
    {
     "id": "pt3",
     "ref": null
    }
   ]
  }
 ]
}
